### ISSUE TITLE
Provide fixed versions - build failes

### ISSUE THREAD

**Issue by mmack** [aporeto-inc/kubepox#17]
Please provide fixed versions for k8s.io/api and k8s.io/apimachinery.

My build fails somewhere and my best guess is it's pulling newer versions.

```
 go build -o kubepox cmd/kubepox/main.go 
# github.com/aporeto-inc/kubepox/vendor/k8s.io/client-go/discovery
vendor/k8s.io/client-go/discovery/restmapper.go:42:75: undefined: meta.VersionInterfacesFunc
vendor/k8s.io/client-go/discovery/restmapper.go:176:19: undefined: meta.VersionInterfacesFunc

```

**Comment by bvandewalle** [comment]
Hi @mmack 
Thanks for the good catch, API Machinery master indeed broke the dependency for client-go.
This should now be fixed with a branch dependency on API Machinery that will match what client-go requires.
rerun `dep ensure` and it should work.

**Comment by mmack** [comment]
Thanks that helped.
