### ISSUE TITLE
Please provide binary release.

### ISSUE THREAD

**Issue by mingfang** [aporeto-inc/kubepox#6]
Hi,
Can you please provide a binary release?
thanks

**Comment by bvandewalle** [comment]
Hi, It should be pretty easy to build, will add some instructions on our README :-)

**Comment by ecourreges-orange** [comment]
> 
> 
> Hi, It should be pretty easy to build, will add some instructions on our README :-)

Hello, I don't see instructions in the readme.
Thanks in advance

**Comment by ecourreges-orange** [comment]
> 
> 
> > Hi, It should be pretty easy to build, will add some instructions on our README :-)
> 
> Hello, I don't see instructions in the readme.
> Thanks in advance

I went ahead and fixed compilation and added Readme in PR https://github.com/aporeto-inc/kubepox/pull/20
